apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bharat-app-static-pvc
  namespace: bharat-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bharat-app-media-pvc
  namespace: bharat-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2-csi

