apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bharat-app-pvc
  namespace: bharat-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2-csi

